### ISSUE TITLE
navbar is aligned to the right on firefox

### ISSUE THREAD

**Issue by vascorsd** [bigskysoftware/missing#48] opened 2024-04-10 03:22 UTC
I was following the docs and implemented the navbar as described and followed the same dom as used on the main missing.css site but somehow I couldn't get it to align at the center as the missing.css site shows.

After some try outs, removing and changing the dom, it seems the actual problem is that I was using the .min.css file instead of just the .css file.

It seems the .min.css if broken and applies different rules which make the navbar aligned to the right, only on firefox. It seems on chromium it shows ok.

reproduction:
 - open firefox (I'm using latest version 124.0.1 on linux)
 - go to https://missing.style/docs/
 - open the debug/dom view
 - change the line with `<link rel="stylesheet" href="/dist/missing.css">` to `<link rel="stylesheet" href="/dist/missing.min.css">` 
 - see the navbar alignment changing

the fix was in my case to stop using the .min.css version and use the .css version.

**Comment by j4mie** [comment] 2024-05-06 09:19
Looks like a duplicate of #32 (with the new information that this only affects the `.min.css` build)

**Comment by dz4k** [comment] 2024-06-13 16:37
this is currently fixed on the website & will be fixed in the next release of the library

**Closed by dz4k** 2024-06-13 16:37 UTC
